### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by yiranzai** [gnwzkd/klock#5]
需要变化颜色以及样式防止烧屏

**Comment by gnwzkd** [comment]
@yiranzai 因为时间和天气已经占满了屏幕，所以不能用移动位置的方式。我做了一个设置，可以在每天的某个时段显示变换的扫描线，就像某些烧屏“修复”软件做的那样。
但我觉得这并没什么意义，如果你的旧设备还有些价值，我不建议将它作此用途。毕竟所谓的防烧屏其实并不能保护屏幕，只能扩大老化区域趋近老化程度。
